// Generated by IP Generator (Version 2018.1B2 build 28960)
// Module Instantiation Template
// Insert the following codes into your Verilog file.
//   * Change <InstanceName> to your own instance name.
//   * Fill in your own signal names in the port connections.

ram <InstanceName> (
    .wr_data(),
    .addr(),
    .wr_en(),
    .clk(),
    .rst(),
    .rd_data());
