// Generated by IP Generator (Version 2018.1B3 build 30354)
// Module Instantiation Template
// Insert the following codes into your Verilog file.
//   * Change <InstanceName> to your own instance name.
//   * Fill in your own signal names in the port connections.

test <InstanceName> (
    .a_addr(),
    .a_wr_data(),
    .a_rd_data(),
    .a_wr_en(),
    .a_clk(),
    .a_rst(),
    .b_addr(),
    .b_wr_data(),
    .b_rd_data(),
    .b_wr_en(),
    .b_clk(),
    .b_rst());
